name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup Lua
      uses: mah0x211/setup-lua@v1
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1.:latest"
          - "5.2.:latest"
          - "5.3.:latest"
          - "5.4.:latest"
          - "lj-v2.1:latest"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: mah0x211/setup-lua@v1
      with:
        versions: ${{ matrix.lua-version }}
    -
      name: Install Tools
      run: |
        sudo apt install lcov -y
        luarocks install testcase
        luarocks install string-trim
        luarocks install string-contains
    -
      name: Install
      run: |
        luarocks make LLSOCKET_COVERAGE=1
    -
      name: Run Test
      run: |
        testcase ./test
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload c coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
